### ISSUE TITLE
Doesn't recognize multiple tickets

### ISSUE THREAD

**Issue by magikid** [bdashrad/hubot-jiralinks#10]
If a message contains multiple tickets, a link is only generated for the first.  For example, we had a similar exchange to this in our chat:

```
@magikid: Starting deployment for PROJ-1 and PROJ-2
@garybot: https://jira-server/browse/PROJ-1
```

It would be nice if the bot responded with multiple messages for multiple tickets.

**Comment by bdashrad** [comment]
missed this, will apply your changes now
